// commits.ts — accessor for the commit history index.
//
// `commits.json` is generated by `scripts/sync-content.mjs` on every build
// (and dev start). Pages call `getCommitsForSnippet(id)` rather than
// reaching into the JSON directly, so the lookup contract stays in one place.

import commitsData from '../data/commits.json';

export interface Commit {
  sha: string;
  /** ISO 8601 commit date. */
  date: string;
  message: string;
}

const COMMITS = commitsData as Record<string, Commit[]>;

/** Returns commits newest-first, or [] if the snippet has none yet. */
export function getCommitsForSnippet(snippetId: string): Commit[] {
  return COMMITS[snippetId] ?? [];
}
